import Image from "next/image";
import Link from "next/link";
import { PortableText } from "@portabletext/react";
import { ArrowRight, BarChart3, Car, CheckCircle2, Clock3, FileCheck, ShieldCheck } from "lucide-react";
import { urlFor } from "@/sanity/lib/image";

const icons = { car: Car, shield: ShieldCheck, file: FileCheck, chart: BarChart3 };
export function FeatureCards({ features }: { features?: Array<{ title: string; description: string; icon?: keyof typeof icons }> }) { const fallback: Array<{ title: string; description: string; icon: keyof typeof icons }> = [{ title: "Vehicle records", description: "Keep registration, vehicle and ownership details in one dependable place.", icon: "car" }, { title: "Insurance visibility", description: "Stay ahead of policies and renewal dates with clear status at a glance.", icon: "shield" }, { title: "PUC compliance", description: "Track certificates and expiry dates without searching through paperwork.", icon: "file" }]; return <div className="grid-3">{(features?.length ? features : fallback).slice(0,3).map((feature, index) => { const Icon = icons[feature.icon || fallback[index].icon] || Car; return <article className="card" key={feature.title}><div className="icon-box"><Icon size={21}/></div><h3>{feature.title}</h3><p>{feature.description}</p></article>; })}</div>; }
export function formatPostDate(date?: string) { return date ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(date)) : null; }
export function readingTime(value?: any[]) { const words = value?.reduce((total, block) => total + (block.children?.reduce((count: number, child: any) => count + (child.text?.trim().split(/\s+/).filter(Boolean).length || 0), 0) || 0), 0) || 0; return Math.max(1, Math.ceil(words / 200)); }
export function PostCard({ post, compact = false }: { post: Record<string, any>; compact?: boolean }) { const image = post.featuredImage ? urlFor(post.featuredImage).width(840).height(480).fit("crop").url() : null; const date = formatPostDate(post.publishedAt); return <article className={`post-card${compact ? " post-card-compact" : ""}`}><Link href={`/blog/${post.slug}`} className="post-card-link" aria-label={`Read ${post.title}`}>{image ? <Image className="post-image" src={image} alt={post.featuredImage?.alt || post.title} width={840} height={480} sizes="(max-width: 760px) 100vw, (max-width: 1100px) 50vw, 33vw"/> : <div className="post-image post-image-placeholder" aria-hidden="true"/>}<div className="post-body"><div className="post-card-meta"><span className="tag">{post.categories?.[0]?.title || "Fleet insights"}</span>{date && <span>{date}</span>}</div><h3>{post.title}</h3><p>{post.excerpt || "Read the latest practical insights for managing your fleet."}</p><span className="post-read">Read article <ArrowRight size={15}/></span></div></Link></article>; }
export function PostCards({ posts }: { posts: Array<Record<string, any>> }) { if (!posts.length) return <div className="empty blog-empty"><h2>No articles published yet.</h2><p>New fleet insights will appear here as soon as they are published.</p></div>; return <div className="post-grid">{posts.map((post) => <PostCard post={post} key={post._id || post.slug}/>)}</div>; }
export function RichContent({ value }: { value?: any[] }) { return value?.length ? <div className="prose"><PortableText value={value} components={{ types: { image: ({ value }) => { const image = value?.asset ? urlFor(value).width(1400).fit("max").url() : null; return image ? <figure><Image src={image} alt={value.alt || ""} width={1400} height={900} sizes="(max-width: 760px) 100vw, 760px"/><figcaption>{value.alt}</figcaption></figure> : null; } }, marks: { link: ({ value, children }) => <a href={value?.href} target={value?.blank ? "_blank" : undefined} rel={value?.blank ? "noreferrer" : undefined}>{children}</a>, code: ({ children }) => <code>{children}</code> }, block: { blockquote: ({ children }) => <blockquote>{children}</blockquote>, code: ({ children }) => <pre><code>{children}</code></pre> } }} /></div> : null; }
export function Checks() { return <ul className="check-list"><li><CheckCircle2 className="check" size={19}/>One place for the records your team needs daily.</li><li><CheckCircle2 className="check" size={19}/>Clear status tracking that supports timely action.</li><li><CheckCircle2 className="check" size={19}/>A focused interface built for busy operations teams.</li></ul>; }
